[package]
name = "main"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@unity3d.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1.17"
clap = { version = "2.29", features = ["yaml"] }

inverted_index = { path = "./inverted-index/" }
web = { path = "./web/" }

