[package]
name = "rpc"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@subnetzero.io>"]

[dependencies]
uuid = { version = "0.5", features = ["v4", "serde"] }
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
rusqlite = "0.13.0"
