[package]
name = "web"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@subnetzero.io>"]

[dependencies]
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
futures = "0.1.17"
hyper = "0.11"
regex = "0.2"
rusqlite = "0.13.0"
rpc = { path = "../rpc" }
